### ISSUE TITLE
Error on WP 5.8.3 and latest wp-saml-auth 2.0

### ISSUE THREAD

**Issue by patschi** [pantheon-systems/wp-saml-auth#276]
When activating (and not yet fully setting up the plugin) I was receiving automated emails from my Wordpress instance reporting errors from the extension:

```
An error of type E_ERROR was caused in line 141 of the file wp-content/plugins/wp-saml-auth/vendor/onelogin/php-saml/src/Saml2/Settings.php. 
Error message: Uncaught OneLogin\Saml2\Error: Invalid array settings: idp_cert_or_fingerprint_not_found_and_required in wp-content/plugins/wp-saml-auth/vendor/onelogin/php-saml/src/Saml2/Settings.php:141
Stack trace:
#0 wp-content/plugins/wp-saml-auth/vendor/onelogin/php-saml/src/Saml2/Auth.php(177): OneLogin\Saml2\Settings->__construct()
#1 wp-content/plugins/wp-saml-auth/inc/class-wp-saml-auth.php(86): OneLogin\Saml2\Auth->__construct()
#2 wp-content/plugins/wp-saml-auth/inc/class-wp-saml-auth.php(66): WP_SAML_Auth->set_provider()
#3 wp-content/plugins/wp-saml-auth/inc/class-wp-saml-auth.php(184): WP_SAML_Auth->get_provider()
#4 wp-includes/class-wp-hook.php(303): WP_SAML_Auth->action_wp_logout()
#5 wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#6 wp-includes/plugin.php(470): WP_Hook->do_action()
#7 wp-includes/pluggable.php(644): do_action()
#8 wp-content/plugins/better-wp-security/core/lockout.php(793): wp_logout()
#9 wp-content/plugins/better-wp-security/core/modules/network-brute-force/class-itsec-ipcheck.php(46): ITSEC_Lockout->execute_lock()
#10 wp-includes/class-wp-hook.php(303): ITSEC_IPCheck->filter_authenticate()
#11 wp-includes/plugin.php(189): WP_Hook->apply_filters()
#12 wp-includes/pluggable.php(593): apply_filters()
#13 wp-includes/user.php(95): wp_authenticate()
#14 wp-login.php(1142): wp_signon()
#15 {main}
  thrown
```

I think this is related to the upgrade of the OneLogin library.

**Comment by danielbachhuber** [comment]
Hey @patschi,

Thanks for the report! Which PHP version are you running?

**Comment by patschi** [comment]
> Which PHP version are you running?

PHP 8.0.13

**Comment by danielbachhuber** [comment]
Here's the diff between `onelogin/php-saml` 3.6.1 and 4.0.0: https://github.com/onelogin/php-saml/compare/3.6.1...4.0.0

It looks like there was only one (minimal) change in the `src/` directory: https://github.com/onelogin/php-saml/compare/3.6.1...4.0.0#diff-b61383b8af6d0832f4319fa27427cb2ab7c7932efc870be2a558145fbd828da0

When you upgraded to WP SAML Auth v2.0.0, did you also change your PHP version?

Additionally, given the error message (`Invalid array settings: idp_cert_or_fingerprint_not_found_and_required`), can you make sure your config file is properly constructed? Feel free to share it here with the secrets removed if you need a second pair of eyes.
